# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fleaMarket' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
pod 'KFSwiftImageLoader', '~> 2.0'


  # Pods for fleaMarket

  target 'fleaMarketTests' do
    inherit! :search_paths
    # Pods for testing

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
pod 'KFSwiftImageLoader', '~> 2.0'

  end

  target 'fleaMarketUITests' do
    inherit! :search_paths
    # Pods for testing
    
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '9.0'
    use_frameworks!
    pod 'KFSwiftImageLoader', '~> 2.0'
    
  end

end
