# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
# 
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Create a root user with admin privilege
#User.create(username: 'root', email: 'root@example.com', mobile: '0987654321', password: 'GFEC01', admin: true)

# Create data for postcode table
Postcode. create(name:"台北市")#1
Postcode. create(name:"新北市")#2
Postcode. create(name:"基隆市")#3
Postcode. create(name:"宜蘭縣")#4
Postcode. create(name:"桃園縣")#5
Postcode. create(postcode: 300, name:"新竹市")#6
Postcode. create(name:"新竹縣")#7
Postcode. create(name:"苗栗縣")#8
Postcode. create(name:"台中市")#9
Postcode. create(name:"彰化縣")#10
Postcode. create(name:"南投縣")#11
Postcode. create(postcode: 600, name:"嘉義市")#12
Postcode. create(name:"嘉義縣")#13
Postcode. create(name:"雲林縣")#14
Postcode. create(name:"台南市")#15
Postcode. create(name:"高雄市")#16
Postcode. create(name:"澎湖縣")#17
Postcode. create(name:"屏東縣")#18
Postcode. create(name:"台東縣")#19
Postcode. create(name:"花蓮縣")#20
Postcode. create(name:"金門縣")#21
Postcode. create(name:"連江縣")#22
Postcode. create(name:"南海諸島")#23
Postcode. create(postcode: 100, name:"中正區", city_id:1)
Postcode. create(postcode: 103, name:"大同區", city_id:1)
Postcode. create(postcode: 104, name:"中山區", city_id:1)
Postcode. create(postcode: 105, name:"松山區", city_id:1)
Postcode. create(postcode: 106, name:"大安區", city_id:1)
Postcode. create(postcode: 108, name:"萬華區", city_id:1)
Postcode. create(postcode: 110, name:"信義區", city_id:1)
Postcode. create(postcode: 111, name:"士林區", city_id:1)
Postcode. create(postcode: 112, name:"北投區", city_id:1)
Postcode. create(postcode: 114, name:"內湖區", city_id:1)
Postcode. create(postcode: 115, name:"南港區", city_id:1)
Postcode. create(postcode: 116, name:"文山區", city_id:1)
Postcode. create(postcode: 207, name:"萬　里", city_id:2)
Postcode. create(postcode: 208, name:"金　山", city_id:2)
Postcode. create(postcode: 220, name:"板　橋", city_id:2)
Postcode. create(postcode: 221, name:"汐　止", city_id:2)
Postcode. create(postcode: 222, name:"深　坑", city_id:2)
Postcode. create(postcode: 223, name:"石　碇", city_id:2)
Postcode. create(postcode: 224, name:"瑞　芳", city_id:2)
Postcode. create(postcode: 226, name:"平　溪", city_id:2)
Postcode. create(postcode: 227, name:"雙　溪", city_id:2)
Postcode. create(postcode: 228, name:"貢　寮", city_id:2)
Postcode. create(postcode: 231, name:"新　店", city_id:2)
Postcode. create(postcode: 232, name:"坪　林", city_id:2)
Postcode. create(postcode: 233, name:"烏　來", city_id:2)
Postcode. create(postcode: 234, name:"永　和", city_id:2)
Postcode. create(postcode: 235, name:"中　和", city_id:2)
Postcode. create(postcode: 236, name:"土　城", city_id:2)
Postcode. create(postcode: 237, name:"三　峽", city_id:2)
Postcode. create(postcode: 238, name:"樹　林", city_id:2)
Postcode. create(postcode: 239, name:"鶯　歌", city_id:2)
Postcode. create(postcode: 241, name:"三　重", city_id:2)
Postcode. create(postcode: 242, name:"新　莊", city_id:2)
Postcode. create(postcode: 243, name:"泰　山", city_id:2)
Postcode. create(postcode: 244, name:"林　口", city_id:2)
Postcode. create(postcode: 247, name:"蘆　洲", city_id:2)
Postcode. create(postcode: 248, name:"五　股", city_id:2)
Postcode. create(postcode: 249, name:"八　里", city_id:2)
Postcode. create(postcode: 251, name:"淡　水", city_id:2)
Postcode. create(postcode: 252, name:"三　芝", city_id:2)
Postcode. create(postcode: 253, name:"石　門", city_id:2)
Postcode. create(postcode: 200, name:"仁愛區", city_id:3)
Postcode. create(postcode: 201, name:"信義區", city_id:3)
Postcode. create(postcode: 202, name:"中正區", city_id:3)
Postcode. create(postcode: 203, name:"中山區", city_id:3)
Postcode. create(postcode: 204, name:"安樂區", city_id:3)
Postcode. create(postcode: 205, name:"暖暖區", city_id:3)
Postcode. create(postcode: 206, name:"七堵區", city_id:3)
Postcode. create(postcode: 260, name:"宜　蘭", city_id:4)
Postcode. create(postcode: 261, name:"頭　城", city_id:4)
Postcode. create(postcode: 262, name:"礁　溪", city_id:4)
Postcode. create(postcode: 263, name:"壯　圍", city_id:4)
Postcode. create(postcode: 264, name:"員　山", city_id:4)
Postcode. create(postcode: 265, name:"羅　東", city_id:4)
Postcode. create(postcode: 266, name:"三　星", city_id:4)
Postcode. create(postcode: 267, name:"大　同", city_id:4)
Postcode. create(postcode: 268, name:"五　結", city_id:4)
Postcode. create(postcode: 269, name:"冬　山", city_id:4)
Postcode. create(postcode: 270, name:"蘇　澳", city_id:4)
Postcode. create(postcode: 272, name:"南　澳", city_id:4)
Postcode. create(postcode: 320, name:"中  壢", city_id:5)
Postcode. create(postcode: 324, name:"平  鎮", city_id:5)
Postcode. create(postcode: 325, name:"龍  潭", city_id:5)
Postcode. create(postcode: 326, name:"楊  梅", city_id:5)
Postcode. create(postcode: 327, name:"新  屋", city_id:5)
Postcode. create(postcode: 328, name:"觀  音", city_id:5)
Postcode. create(postcode: 330, name:"桃  園", city_id:5)
Postcode. create(postcode: 333, name:"龜  山", city_id:5)
Postcode. create(postcode: 334, name:"八  德", city_id:5)
Postcode. create(postcode: 335, name:"大  溪", city_id:5)
Postcode. create(postcode: 336, name:"復  興", city_id:5)
Postcode. create(postcode: 337, name:"大  園", city_id:5)
Postcode. create(postcode: 338, name:"蘆  竹", city_id:5)
Postcode. create(postcode: 302, name:"竹  北", city_id:7)
Postcode. create(postcode: 303, name:"湖  口", city_id:7)
Postcode. create(postcode: 304, name:"新  豐", city_id:7)
Postcode. create(postcode: 305, name:"新  埔", city_id:7)
Postcode. create(postcode: 306, name:"關  西", city_id:7)
Postcode. create(postcode: 307, name:"芎　林", city_id:7)
Postcode. create(postcode: 308, name:"寶  山", city_id:7)
Postcode. create(postcode: 310, name:"竹  東", city_id:7)
Postcode. create(postcode: 311, name:"五  峰", city_id:7)
Postcode. create(postcode: 312, name:"橫  山", city_id:7)
Postcode. create(postcode: 313, name:"尖  石", city_id:7)
Postcode. create(postcode: 314, name:"北  埔", city_id:7)
Postcode. create(postcode: 315, name:"峨  眉", city_id:7)
Postcode. create(postcode: 350, name:"竹  南", city_id:8)
Postcode. create(postcode: 351, name:"頭  份", city_id:8)
Postcode. create(postcode: 352, name:"三  灣", city_id:8)
Postcode. create(postcode: 353, name:"南  庄", city_id:8)
Postcode. create(postcode: 354, name:"獅  潭", city_id:8)
Postcode. create(postcode: 356, name:"後  龍", city_id:8)
Postcode. create(postcode: 357, name:"通  霄", city_id:8)
Postcode. create(postcode: 358, name:"苑  裡", city_id:8)
Postcode. create(postcode: 360, name:"苗  栗", city_id:8)
Postcode. create(postcode: 361, name:"造  橋", city_id:8)
Postcode. create(postcode: 362, name:"頭  屋", city_id:8)
Postcode. create(postcode: 363, name:"公  館", city_id:8)
Postcode. create(postcode: 364, name:"大  湖", city_id:8)
Postcode. create(postcode: 365, name:"泰  安", city_id:8)
Postcode. create(postcode: 366, name:"銅  鑼", city_id:8)
Postcode. create(postcode: 367, name:"三  義", city_id:8)
Postcode. create(postcode: 368, name:"西  湖", city_id:8)
Postcode. create(postcode: 369, name:"卓  蘭", city_id:8)
Postcode. create(postcode: 400, name:"中  區", city_id:9)
Postcode. create(postcode: 401, name:"東  區", city_id:9)
Postcode. create(postcode: 402, name:"南  區", city_id:9)
Postcode. create(postcode: 403, name:"西  區", city_id:9)
Postcode. create(postcode: 404, name:"北  區", city_id:9)
Postcode. create(postcode: 406, name:"北屯區", city_id:9)
Postcode. create(postcode: 407, name:"西屯區", city_id:9)
Postcode. create(postcode: 408, name:"南屯區", city_id:9)
Postcode. create(postcode: 411, name:"太  平", city_id:9)
Postcode. create(postcode: 412, name:"大  里", city_id:9)
Postcode. create(postcode: 413, name:"霧  峰", city_id:9)
Postcode. create(postcode: 414, name:"烏  日", city_id:9)
Postcode. create(postcode: 420, name:"豐  原", city_id:9)
Postcode. create(postcode: 421, name:"后  里", city_id:9)
Postcode. create(postcode: 422, name:"石  岡", city_id:9)
Postcode. create(postcode: 423, name:"東  勢", city_id:9)
Postcode. create(postcode: 424, name:"和  平", city_id:9)
Postcode. create(postcode: 426, name:"新  社", city_id:9)
Postcode. create(postcode: 427, name:"潭  子", city_id:9)
Postcode. create(postcode: 428, name:"大  雅", city_id:9)
Postcode. create(postcode: 429, name:"神  岡", city_id:9)
Postcode. create(postcode: 432, name:"大  肚", city_id:9)
Postcode. create(postcode: 433, name:"沙  鹿", city_id:9)
Postcode. create(postcode: 434, name:"龍  井", city_id:9)
Postcode. create(postcode: 435, name:"梧　棲", city_id:9)
Postcode. create(postcode: 436, name:"清  水", city_id:9)
Postcode. create(postcode: 437, name:"大  甲", city_id:9)
Postcode. create(postcode: 438, name:"外  埔", city_id:9)
Postcode. create(postcode: 439, name:"大  安", city_id:9)
Postcode. create(postcode: 500, name:"彰  化", city_id:10)
Postcode. create(postcode: 502, name:"芬  園", city_id:10)
Postcode. create(postcode: 503, name:"花  壇", city_id:10)
Postcode. create(postcode: 504, name:"秀  水", city_id:10)
Postcode. create(postcode: 505, name:"鹿  港", city_id:10)
Postcode. create(postcode: 506, name:"福  興", city_id:10)
Postcode. create(postcode: 507, name:"線  西", city_id:10)
Postcode. create(postcode: 508, name:"和  美", city_id:10)
Postcode. create(postcode: 509, name:"伸  港", city_id:10)
Postcode. create(postcode: 510, name:"員  林", city_id:10)
Postcode. create(postcode: 511, name:"社  頭", city_id:10)
Postcode. create(postcode: 512, name:"永  靖", city_id:10)
Postcode. create(postcode: 513, name:"埔  心", city_id:10)
Postcode. create(postcode: 514, name:"溪  湖", city_id:10)
Postcode. create(postcode: 515, name:"大  村", city_id:10)
Postcode. create(postcode: 516, name:"埔  鹽", city_id:10)
Postcode. create(postcode: 520, name:"田  中", city_id:10)
Postcode. create(postcode: 521, name:"北  斗", city_id:10)
Postcode. create(postcode: 522, name:"田  尾", city_id:10)
Postcode. create(postcode: 523, name:"埤  頭", city_id:10)
Postcode. create(postcode: 524, name:"溪  州", city_id:10)
Postcode. create(postcode: 525, name:"竹  塘", city_id:10)
Postcode. create(postcode: 526, name:"二  林", city_id:10)
Postcode. create(postcode: 527, name:"大  城", city_id:10)
Postcode. create(postcode: 528, name:"芳  苑", city_id:10)
Postcode. create(postcode: 530, name:"二  水", city_id:10)
Postcode. create(postcode: 540, name:"南  投", city_id:11)
Postcode. create(postcode: 541, name:"中  寮", city_id:11)
Postcode. create(postcode: 542, name:"草  屯", city_id:11)
Postcode. create(postcode: 544, name:"國  姓", city_id:11)
Postcode. create(postcode: 545, name:"埔  里", city_id:11)
Postcode. create(postcode: 546, name:"仁  愛", city_id:11)
Postcode. create(postcode: 551, name:"名  間", city_id:11)
Postcode. create(postcode: 552, name:"集  集", city_id:11)
Postcode. create(postcode: 553, name:"水  里", city_id:11)
Postcode. create(postcode: 555, name:"魚  池", city_id:11)
Postcode. create(postcode: 556, name:"信  義", city_id:11)
Postcode. create(postcode: 557, name:"竹  山", city_id:11)
Postcode. create(postcode: 558, name:"鹿  谷", city_id:11)
Postcode. create(postcode: 602, name:"番  路", city_id:13)
Postcode. create(postcode: 603, name:"梅  山", city_id:13)
Postcode. create(postcode: 604, name:"竹  崎", city_id:13)
Postcode. create(postcode: 605, name:"阿里山", city_id:13)
Postcode. create(postcode: 606, name:"中  埔", city_id:13)
Postcode. create(postcode: 607, name:"大  埔", city_id:13)
Postcode. create(postcode: 608, name:"水  上", city_id:13)
Postcode. create(postcode: 611, name:"鹿  草", city_id:13)
Postcode. create(postcode: 612, name:"太  保", city_id:13)
Postcode. create(postcode: 613, name:"朴　子", city_id:13)
Postcode. create(postcode: 614, name:"東  石", city_id:13)
Postcode. create(postcode: 615, name:"六  腳", city_id:13)
Postcode. create(postcode: 616, name:"新  港", city_id:13)
Postcode. create(postcode: 621, name:"民  雄", city_id:13)
Postcode. create(postcode: 622, name:"大  林", city_id:13)
Postcode. create(postcode: 623, name:"溪  口", city_id:13)
Postcode. create(postcode: 624, name:"義  竹", city_id:13)
Postcode. create(postcode: 625, name:"布  袋", city_id:13)
Postcode. create(postcode: 630, name:"斗  六", city_id:14)
Postcode. create(postcode: 631, name:"大  埤", city_id:14)
Postcode. create(postcode: 632, name:"虎  尾", city_id:14)
Postcode. create(postcode: 633, name:"土  庫", city_id:14)
Postcode. create(postcode: 634, name:"褒  忠", city_id:14)
Postcode. create(postcode: 635, name:"東  勢", city_id:14)
Postcode. create(postcode: 636, name:"台  西", city_id:14)
Postcode. create(postcode: 637, name:"崙  背", city_id:14)
Postcode. create(postcode: 638, name:"麥  寮", city_id:14)
Postcode. create(postcode: 640, name:"斗  六", city_id:14)
Postcode. create(postcode: 643, name:"林  內", city_id:14)
Postcode. create(postcode: 646, name:"古  坑", city_id:14)
Postcode. create(postcode: 647, name:"荊  桐", city_id:14)
Postcode. create(postcode: 648, name:"西  螺", city_id:14)
Postcode. create(postcode: 649, name:"二  崙", city_id:14)
Postcode. create(postcode: 651, name:"北  港", city_id:14)
Postcode. create(postcode: 652, name:"水  林", city_id:14)
Postcode. create(postcode: 653, name:"口  湖", city_id:14)
Postcode. create(postcode: 654, name:"四  湖", city_id:14)
Postcode. create(postcode: 655, name:"元  長", city_id:14)
Postcode. create(postcode: 700, name:"中  區", city_id:15)
Postcode. create(postcode: 701, name:"東  區", city_id:15)
Postcode. create(postcode: 702, name:"南  區", city_id:15)
Postcode. create(postcode: 703, name:"西  區", city_id:15)
Postcode. create(postcode: 704, name:"北  區", city_id:15)
Postcode. create(postcode: 708, name:"安平區", city_id:15)
Postcode. create(postcode: 709, name:"安南區", city_id:15)
Postcode. create(postcode: 710, name:"永  康", city_id:15)
Postcode. create(postcode: 711, name:"歸  仁", city_id:15)
Postcode. create(postcode: 712, name:"新  化", city_id:15)
Postcode. create(postcode: 713, name:"左  鎮", city_id:15)
Postcode. create(postcode: 714, name:"玉  井", city_id:15)
Postcode. create(postcode: 715, name:"楠  西", city_id:15)
Postcode. create(postcode: 716, name:"南  化", city_id:15)
Postcode. create(postcode: 717, name:"仁  德", city_id:15)
Postcode. create(postcode: 718, name:"關  廟", city_id:15)
Postcode. create(postcode: 719, name:"龍  崎", city_id:15)
Postcode. create(postcode: 720, name:"官  田", city_id:15)
Postcode. create(postcode: 721, name:"麻  豆", city_id:15)
Postcode. create(postcode: 722, name:"佳  里", city_id:15)
Postcode. create(postcode: 723, name:"西  港", city_id:15)
Postcode. create(postcode: 724, name:"七  股", city_id:15)
Postcode. create(postcode: 725, name:"將  軍", city_id:15)
Postcode. create(postcode: 726, name:"學  甲", city_id:15)
Postcode. create(postcode: 727, name:"北  門", city_id:15)
Postcode. create(postcode: 730, name:"新  營", city_id:15)
Postcode. create(postcode: 731, name:"後  壁", city_id:15)
Postcode. create(postcode: 732, name:"白  河", city_id:15)
Postcode. create(postcode: 733, name:"東  山", city_id:15)
Postcode. create(postcode: 734, name:"六  甲", city_id:15)
Postcode. create(postcode: 735, name:"下  營", city_id:15)
Postcode. create(postcode: 736, name:"柳  營", city_id:15)
Postcode. create(postcode: 737, name:"鹽  水", city_id:15)
Postcode. create(postcode: 741, name:"善  化", city_id:15)
Postcode. create(postcode: 742, name:"大  內", city_id:15)
Postcode. create(postcode: 743, name:"山  上", city_id:15)
Postcode. create(postcode: 744, name:"新  市", city_id:15)
Postcode. create(postcode: 745, name:"安  定", city_id:15)
Postcode. create(postcode: 800, name:"新興區", city_id:16)
Postcode. create(postcode: 801, name:"前金區", city_id:16)
Postcode. create(postcode: 802, name:"苓雅區", city_id:16)
Postcode. create(postcode: 803, name:"鹽埕區", city_id:16)
Postcode. create(postcode: 804, name:"鼓山區", city_id:16)
Postcode. create(postcode: 805, name:"旗津區", city_id:16)
Postcode. create(postcode: 806, name:"前鎮區", city_id:16)
Postcode. create(postcode: 807, name:"三民區", city_id:16)
Postcode. create(postcode: 811, name:"楠梓區", city_id:16)
Postcode. create(postcode: 812, name:"小港區", city_id:16)
Postcode. create(postcode: 813, name:"左營區", city_id:16)
Postcode. create(postcode: 814, name:"仁  武", city_id:16)
Postcode. create(postcode: 815, name:"大  社", city_id:16)
Postcode. create(postcode: 820, name:"岡  山", city_id:16)
Postcode. create(postcode: 821, name:"路  竹", city_id:16)
Postcode. create(postcode: 822, name:"阿  蓮", city_id:16)
Postcode. create(postcode: 823, name:"田  寮", city_id:16)
Postcode. create(postcode: 824, name:"燕  巢", city_id:16)
Postcode. create(postcode: 825, name:"橋  頭", city_id:16)
Postcode. create(postcode: 826, name:"梓  官", city_id:16)
Postcode. create(postcode: 827, name:"彌  陀", city_id:16)
Postcode. create(postcode: 828, name:"永  安", city_id:16)
Postcode. create(postcode: 829, name:"湖  內", city_id:16)
Postcode. create(postcode: 830, name:"鳳  山", city_id:16)
Postcode. create(postcode: 831, name:"大  寮", city_id:16)
Postcode. create(postcode: 832, name:"林  園", city_id:16)
Postcode. create(postcode: 833, name:"鳥  松", city_id:16)
Postcode. create(postcode: 840, name:"大  樹", city_id:16)
Postcode. create(postcode: 842, name:"旗  山", city_id:16)
Postcode. create(postcode: 843, name:"美  濃", city_id:16)
Postcode. create(postcode: 844, name:"六  龜", city_id:16)
Postcode. create(postcode: 845, name:"內  門", city_id:16)
Postcode. create(postcode: 846, name:"杉  林", city_id:16)
Postcode. create(postcode: 847, name:"甲  仙", city_id:16)
Postcode. create(postcode: 848, name:"桃  源", city_id:16)
Postcode. create(postcode: 849, name:"三  民", city_id:16)
Postcode. create(postcode: 851, name:"茂  林", city_id:16)
Postcode. create(postcode: 852, name:"茄  萣", city_id:16)
Postcode. create(postcode: 880, name:"馬  公", city_id:17)
Postcode. create(postcode: 881, name:"西  嶼", city_id:17)
Postcode. create(postcode: 882, name:"望  安", city_id:17)
Postcode. create(postcode: 883, name:"七  美", city_id:17)
Postcode. create(postcode: 884, name:"白  沙", city_id:17)
Postcode. create(postcode: 885, name:"湖  西", city_id:17)
Postcode. create(postcode: 900, name:"屏  東", city_id:18)
Postcode. create(postcode: 901, name:"三  地", city_id:18)
Postcode. create(postcode: 902, name:"霧  台", city_id:18)
Postcode. create(postcode: 903, name:"瑪  家", city_id:18)
Postcode. create(postcode: 904, name:"九  如", city_id:18)
Postcode. create(postcode: 905, name:"里  港", city_id:18)
Postcode. create(postcode: 906, name:"高  樹", city_id:18)
Postcode. create(postcode: 907, name:"鹽  埔", city_id:18)
Postcode. create(postcode: 908, name:"長  治", city_id:18)
Postcode. create(postcode: 909, name:"麟  洛", city_id:18)
Postcode. create(postcode: 911, name:"竹  田", city_id:18)
Postcode. create(postcode: 912, name:"內  埔", city_id:18)
Postcode. create(postcode: 913, name:"萬  丹", city_id:18)
Postcode. create(postcode: 920, name:"潮  州", city_id:18)
Postcode. create(postcode: 921, name:"泰  武", city_id:18)
Postcode. create(postcode: 922, name:"來  義", city_id:18)
Postcode. create(postcode: 923, name:"萬  巒", city_id:18)
Postcode. create(postcode: 924, name:"崁  頂", city_id:18)
Postcode. create(postcode: 925, name:"新  埤", city_id:18)
Postcode. create(postcode: 926, name:"南  州", city_id:18)
Postcode. create(postcode: 927, name:"林  邊", city_id:18)
Postcode. create(postcode: 928, name:"東  港", city_id:18)
Postcode. create(postcode: 929, name:"琉  球", city_id:18)
Postcode. create(postcode: 931, name:"佳  冬", city_id:18)
Postcode. create(postcode: 932, name:"新  園", city_id:18)
Postcode. create(postcode: 940, name:"枋  寮", city_id:18)
Postcode. create(postcode: 941, name:"枋  山", city_id:18)
Postcode. create(postcode: 942, name:"春  日", city_id:18)
Postcode. create(postcode: 943, name:"獅  子", city_id:18)
Postcode. create(postcode: 944, name:"車  城", city_id:18)
Postcode. create(postcode: 945, name:"牡  丹", city_id:18)
Postcode. create(postcode: 946, name:"恆  春", city_id:18)
Postcode. create(postcode: 947, name:"滿  州", city_id:18)
Postcode. create(postcode: 950, name:"台  東", city_id:19)
Postcode. create(postcode: 955, name:"鹿  野", city_id:19)
Postcode. create(postcode: 961, name:"成  功", city_id:19)
Postcode. create(postcode: 966, name:"達  仁", city_id:19)
Postcode. create(postcode: 970, name:"花  蓮", city_id:20)
Postcode. create(postcode: 971, name:"新  城", city_id:20)
Postcode. create(postcode: 972, name:"秀  林", city_id:20)
Postcode. create(postcode: 973, name:"吉  安", city_id:20)
Postcode. create(postcode: 974, name:"壽  豐", city_id:20)
Postcode. create(postcode: 975, name:"鳳  林", city_id:20)
Postcode. create(postcode: 976, name:"光  復", city_id:20)
Postcode. create(postcode: 977, name:"豐  濱", city_id:20)
Postcode. create(postcode: 978, name:"瑞  穗", city_id:20)
Postcode. create(postcode: 979, name:"萬  榮", city_id:20)
Postcode. create(postcode: 981, name:"玉  里", city_id:20)
Postcode. create(postcode: 982, name:"卓  溪", city_id:20)
Postcode. create(postcode: 983, name:"富  里", city_id:20)
Postcode. create(postcode: 890, name:"金  沙", city_id:21)
Postcode. create(postcode: 891, name:"金  湖", city_id:21)
Postcode. create(postcode: 892, name:"金  寧", city_id:21)
Postcode. create(postcode: 893, name:"金  城", city_id:21)
Postcode. create(postcode: 894, name:"烈  嶼", city_id:21)
Postcode. create(postcode: 896, name:"烏  坵", city_id:21)
Postcode. create(postcode: 209, name:"南  竿", city_id:22)
Postcode. create(postcode: 210, name:"北  竿", city_id:22)
Postcode. create(postcode: 211, name:"莒  光", city_id:22)
Postcode. create(postcode: 212, name:"東  引", city_id:22)
Postcode. create(postcode: 817, name:"東  沙", city_id:23)
Postcode. create(postcode: 819, name:"南  沙", city_id:23)
Postcode. create(postcode: 290, name:"釣魚台列嶼", city_id:23)